flashcards/accounts/urls.py
from django.conf.urls import url, include
from . import views
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create_account, name='create_account'),
    path('login/', LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='index.html'), name='logout'),
    path('profile/', views.Profile.as_view(), name='profile'),

]

flashcards/flashcards/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('register',include('register.urls')),
    path('retrieval',include('retrieval.urls')),
    path('learning',include('learning.urls')),
]

flashcards/learning/urls.py
from django.conf.urls import url, include
from . import views
from django.urls import path

app_name = 'learning'
urlpatterns = [
    path('learning/', views.learning_list, name='learning_list'),
    path('learning/check_answer', views.check_answer, name='check_answer'),

]

flashcards/register/urls.py
from django.conf.urls import url, include
from . import views
from django.urls import path

app_name = 'register'
urlpatterns = [
    path('regist/', views.word_list, name='word_list'),
    path('regist/add/', views.flashcards_edit, name='word_add'),  # 登録
    path('regist/mod/<int:word_id>/', views.flashcards_edit, name='word_mod'),  # 修正
    path('regist/del/<int:word_id>/', views.flashcards_del, name='word_del'),   # 削除
]

flashcards/retrieval/urls.py
from django.conf.urls import url, include
from . import views
from django.urls import path

app_name = 'retrieval'
urlpatterns = [
    path('retrieval/', views.retrieval_list, name='retrieval_list'),
]

flashcards/learning/models.py
from django.db import models

# Create your models here.

flashcards/register/models.py
from django.db import models

# Create your models here.

class Flashcards(models.Model):
    """flashcards"""
    words = models.CharField('単語', max_length=255)
    meanings = models.CharField('意味', max_length=255)
    part_of_speech = models.CharField('品詞', max_length=255)
    synonym = models.CharField('類義語', max_length=255)
    sentence = models.CharField('例文', max_length=255)


    def __str__(self):
        return self.words

flashcards/accounts/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       #htmlの表示を変更可能にします
       self.fields['username'].widget.attrs['class'] = 'form-control'
       #self.fields['zipcord'].widget.attrs['class'] = 'form-control'
       self.fields['password'].widget.attrs['class'] = 'form-control'

class UserCreateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        #self.fields['zipcord'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

    class Meta:
       model = User
       fields = ("username",  "password1", "password2",)

flashcards/register/forms.py
from django.forms import ModelForm
from register.models import Flashcards

class FlashcardsForm(ModelForm):
    """単語帳フォーム"""
    class Meta:
        model = Flashcards
        fields = ('words', 'meanings', 'part_of_speech', 'synonym', 'sentence', )
        

flashcards/accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.views.generic import CreateView, TemplateView
from .forms import UserCreateForm, LoginForm

#indexページ
class Index(TemplateView):
    template_name = 'index.html'

index = Index.as_view()

#アカウント作成
class Create_Account(CreateView):
    def post(self, request, *args, **kwargs):
        form = UserCreateForm(data=request.POST)
        if form.is_valid():
            form.save()
            #フォームから'username'を読み取る
            username = form.cleaned_data.get('username')
            #フォームから'password1'を読み取る
            password = form.cleaned_data.get('password1')
            #フォームに入力された'username', 'password1'が一致する会員をDBから探し，userに代入
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/')
        return render(request, 'create.html', {'form': form,})

    def get(self, request, *args, **kwargs):
        form = UserCreateForm(request.POST)
        return  render(request, 'create.html', {'form': form,})

create_account = Create_Account.as_view()

#ログイン
class Account_login(View):
    def post(self, request, *arg, **kwargs):
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            user = User.objects.get(username=username)
            login(request, user)
            return redirect('/')
        return render(request, 'login.html', {'form': form,})

    def get(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        return render(request, 'login.html', {'form': form,})

account_login = Account_login.as_view()

#マイページ
class Profile(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'profile.html')

flashcards/learning/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.models import User
from django.views.generic import CreateView, TemplateView
from register.models import Flashcards
from django.db.models import Q
import logging
logger = logging.getLogger('development')
# Create your views here.

def learning_list(request):
    flashcards = Flashcards.objects.only('words')
    #flashcards = Flashcards.objects.filter(name__startwith='query')
    return render(request, 'learning.html', {'flashcards': flashcards})

def check_answer(request):
    answer_words = request.POST.getlist('answer')
    flashcards = Flashcards.objects.all()
    #logger.debug("self.request.POST.get() = " + request.POST.getlist('answer', None)[1])
    temp_list = []
    for i, _ in enumerate(flashcards):
        temp_list.append({
            'flashcards': flashcards[i],
            'answer_words': answer_words[i],
        })
    return render(request, 'check_answer.html', {'temp_list': temp_list,})

flashcards/register/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.models import User
from django.views.generic import CreateView, TemplateView
from register.models import Flashcards
from register.forms import FlashcardsForm
# Create your views here.


def word_list(request):
    flashcards = Flashcards.objects.all()
    return render(request, 'regist.html', {'flashcards': flashcards})

def flashcards_edit(request, word_id=None):
    """単語の編集"""
    if word_id:
        flashcards = get_object_or_404(Flashcards, pk=word_id)
    else:
        flashcards = Flashcards()

    if request.method == 'POST':
        form = FlashcardsForm(request.POST, instance=flashcards)  # POST された request データからフォームを作成
        if form.is_valid():    # フォームのバリデーション
            flashcards = form.save(commit=False)
            flashcards.save()
            return redirect('register:word_list')
    else:    # GET の時
        form = FlashcardsForm(instance=flashcards)

    return render(request, 'edit.html', dict(form=form, word_id=word_id))


def flashcards_del(request, word_id):
    """単語の削除"""
    flashcards = get_object_or_404(Flashcards, pk=word_id)
    flashcards.delete()
    return redirect('register:word_list')

flashcards/retrieval/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.models import User
from django.views.generic import CreateView, TemplateView
from register.models import Flashcards
from django.db.models import Q
# Create your views here.

def retrieval_list(request):
    query_word = request.GET.get("query")
    if query_word:
        flashcards = Flashcards.objects.filter(words__startswith=query_word)
    else:
        flashcards = Flashcards.objects.all()
    #flashcards = Flashcards.objects.filter(name__startwith='query')
    return render(request, 'retrieval.html', {'flashcards': flashcards})

flashcards/accounts/templates/create.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
  <!-- link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}"/-->
</head>
  <body>
    <form method="POST" action="{% url 'accounts:create_account' %}">
      {% csrf_token %}
      <label>ユーザーID</label>
      {{ form.username }}
      {{ form.username.errors }}
      <label>パスワード</label>
      {{ form.password1 }}
      {{ form.password1.errors }}
      <label>パスワード(確認)</label>
      {{ form.password2 }}
      {{ form.password2.errors }}
      <button type = "submit">登録</button>
    </form>
  </body>
</html>

flashcards/accounts/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <link rel="stylesheet" href="{% static 'accounts/css/bootstrap.min.css' %}">
  <body>
    <div class="text-center">
    <h1 class="mt-4 border-bottom">FlashCardsMaker</h1>
    {% if user.id  %}
    <p>ログインしました．</p>
    <p>こんにちは，{{ user.username }}さん</p>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>単語帳</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <a href="{% url 'register:word_list' %}" class="btn btn-outline-primary btn-sm">
              <img src="https://base-ec2.akamaized.net/images/item/origin/93883b4aad8cfba6914e6e5890628084.png" width="150" height="200">
            </a>
          </td>
          <td>
            <a href="{% url 'learning:learning_list' %}" class="btn btn-outline-primary btn-sm">テストする</a>
          </td>
          <td>
            <form action="{% url 'retrieval:retrieval_list' %}" method="get">
              <input name="query" type="text">
              <button type="submit">検索する</button>
            </form>
          </td>
        </tr>
        <tr>
          <td>
            <a href="{% url 'register:word_list' %}" class="btn btn-outline-primary btn-sm">
              <img src="https://images-na.ssl-images-amazon.com/images/I/31n1Vyfhm2L._SX345_BO1,204,203,200_.jpg" width="150" height="200">
            </a>
          </td>
          <td>
            <a href="{% url 'learning:learning_list' %}" class="btn btn-outline-primary btn-sm">テストする</a>
          </td>
          <td>
            <form action="{% url 'retrieval:retrieval_list' %}" method="get">
              <input name="query" type="text">
              <button type="submit">検索する</button>
            </form>
          </td>
        </tr>
      </tbody>
    </table>
    <a href="{% url 'accounts:logout' %}" class="btn btn-outline-primary btn-sm">ログアウトする</a>
    {% else %}
    <a href="{% url 'accounts:login' %}" class="btn btn-outline-primary btn-sm">ログイン</a>
    <a href="{% url 'accounts:create_account' %}" class="btn btn-outline-primary btn-sm">アカウント作成</a>
    {% endif %}
  </div>
  </body>
</html>

flashcards/accounts/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
  <!-- link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}"/-->
</head>
  <body>
    {% if form.errors  %}
    <p>ユーザーID, パスワードが一致しません．</p>
    {% endif %}
    <form method="POST" action="{% url 'accounts:login' %}">
      {% csrf_token %}
      <label>ユーザーID</label>
      {{ form.username }}
      {{ form.username.errors }}
      <label>パスワード</label>
      {{ form.password }}
      {{ form.password.errors }}
      <button type = "submit">ログイン</button>
    </form>
  </body>
</html>

flashcards/accounts/templates/profile.html
<!DOCTYPE html>
<html lang="ja">
<head>
</head>
  <body>
    <h1>こんにちは {{user.username}} さん</h1>
    <p>ユーザーID : {{user.username}}</p>
    <p>パスワード変更</p>
    <a href="{% url 'accounts:index' %}">インデックスページに戻る</a>
  </body>
</html>

flashcards/learning/templates/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{% static 'retrieval/css/bootstrap.min.css' %}">
{% block extra_css %}{% endblock %}
<title>{% block title %}My books{% endblock %}</title>
</head>
<body>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>

</body>
</html>

flashcards/learning/templates/check_answer.html
{% extends "base.html" %}
{% block title %}単語の一覧{% endblock title %}

{% block content %}
    <h4  class="mt-4 border-bottom">結果一覧</h4>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">id</th>
          <th scope="col">単語</th>
          <th scope="col">品詞</th>
          <th scope="col">正解</th>
          <th scope="col">あなたの回答</th>
          <th scope="col">正誤判定</th>
        </tr>
      </thead>
      <tbody>
        {% for index in temp_list %}
        <tr>
          <th scope="row">{{ index.flashcards.id }}</th>
          <td>{{ index.flashcards.words }}</td>
          <td>{{ index.flashcards.part_of_speech }}</td>
          <td>{{ index.flashcards.synonym }}</td>
          <td>{{ index.answer_words }}</td>
          {% if index.flashcards.synonym == index.answer_words %}
            <td>正解🎉😊🎉</td>
          {% else %}
            <td>不正解😭😱😭</td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <a href="{% url 'accounts:index' %}" class="btn btn-primary btn-sm my-3">トップに戻る</a>
{% endblock content %}

flashcards/learning/templates/learning.html
{% extends "base.html" %}
{% block title %}単語のテスト{% endblock title %}

{% block content %}
    <h4  class="mt-4 border-bottom">類義語を答えてください</h4>
    <form action="{% url 'learning:check_answer' %}" method="post">
      {{ form }}
      {% csrf_token %}
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">id</th>
          <th scope="col">単語</th>
          <th scope="col">品詞</th>
          <th scope="col">類義語</th>
        </tr>
      </thead>
      <tbody>
        {% for flashcard in flashcards %}
        <tr>
          <th scope="row">{{ flashcard.id }}</th>
          <td>{{ flashcard.words }}</td>
          <td>{{ flashcard.part_of_speech }}</td>
          <td>
            <input name="answer" type="text">
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <button type="submit">採点する</button>
    </form>
    <a href="{% url 'accounts:index' %}" class="btn btn-primary btn-sm my-3">トップに戻る</a>
{% endblock content %}

flashcards/register/templates/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{% static 'register/css/bootstrap.min.css' %}">
{% block extra_css %}{% endblock %}
<title>{% block title %}My books{% endblock %}</title>
</head>
<body>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
<script src="{% static 'register/js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'register/js/bootstrap.bundle.min.js' %}"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

flashcards/register/templates/edit.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}単語帳の編集{% endblock title %}

{% block content %}
    <h4 class="mt-4 mb-5 border-bottom">単語の編集</h4>
    {% if word_id %}
    <form action="{% url 'register:word_mod' word_id=word_id %}" method="post">
    {% else %}
    <form action="{% url 'register:word_add' %}" method="post">
    {% endif %}
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'register:word_list' %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

flashcards/register/templates/regist.html
{% extends "base.html" %}
{% block title %}単語の一覧{% endblock title %}

{% block content %}
    <h4  class="mt-4 border-bottom">単語一覧</h4>
    <a href="{% url 'register:word_add' %}" class="btn btn-primary btn-sm my-3">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">id</th>
          <th scope="col">単語</th>
          <th scope="col">意味</th>
          <th scope="col">品詞</th>
          <th scope="col">類義語</th>
          <th scope="col">例文</th>
          <th scope="col">編集</th>
        </tr>
      </thead>
      <tbody>
        {% for flashcard in flashcards %}
        <tr>
          <th scope="row">{{ flashcard.id }}</th>
          <td>{{ flashcard.words }}</td>
          <td>{{ flashcard.meanings }}</td>
          <td>{{ flashcard.part_of_speech }}</td>
          <td>{{ flashcard.synonym }}</td>
          <td>{{ flashcard.sentence }}</td>
          <td>
            <a href="{% url 'register:word_mod' word_id=flashcard.id %}" class="btn btn-outline-primary btn-sm">修正</a>
            <a href="{% url 'register:word_del' word_id=flashcard.id %}" class="btn btn-outline-danger btn-sm">削除</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <a href="{% url 'accounts:index' %}" class="btn btn-primary btn-sm my-3">トップに戻る</a>

    {# 削除を確認するモーダル ダイアログ #}
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
     <div class="modal-dialog" role="document">
       <div class="modal-content">
         <div class="modal-header">
           <h5 class="modal-title" id="deleteModalLabel">確認</h5>
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
         </div>
         <div class="modal-body">
           <p>ID: <span id="del_pk"></span> を削除しますか？</p>
         </div>
         <div class="modal-footer">
           <a href="#" class="btn btn-primary" id="del_url">OK</a>
           <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
         </div>
       </div>
     </div>
   </div>

{% endblock content %}

{% block extra_js %}
<script>
  (function(){
     $('.del_confirm').on('click', function () {
       $('#del_pk').text(this.dataset.pk);
       $('#del_url').attr('href', this.dataset.url);
     });
   });
</script>
{% endblock %}

flashcards/retrieval/templates/retrieval.html
{% extends "base.html" %}
{% block title %}単語の一覧{% endblock title %}

{% block content %}
    <h4  class="mt-4 border-bottom">単語一覧</h4>
    <a href="{% url 'register:word_add' %}" class="btn btn-primary btn-sm my-3">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">id</th>
          <th scope="col">単語</th>
          <th scope="col">意味</th>
          <th scope="col">品詞</th>
          <th scope="col">類義語</th>
          <th scope="col">例文</th>
          <th scope="col">編集</th>
        </tr>
      </thead>
      <tbody>
        {% for flashcard in flashcards %}
        <tr>
          <th scope="row">{{ flashcard.id }}</th>
          <td>{{ flashcard.words }}</td>
          <td>{{ flashcard.meanings }}</td>
          <td>{{ flashcard.part_of_speech }}</td>
          <td>{{ flashcard.synonym }}</td>
          <td>{{ flashcard.sentence }}</td>
          <td>
            <a href="{% url 'register:word_mod' word_id=flashcard.id %}" class="btn btn-outline-primary btn-sm">修正</a>
            <a href="{% url 'register:word_del' word_id=flashcard.id %}" class="btn btn-outline-danger btn-sm">削除</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <a href="{% url 'accounts:index' %}" class="btn btn-primary btn-sm my-3">トップに戻る</a>
{% endblock content %}